// Cost scaling will be 1.2x for now
export const colors = [
  {
    id: 1,
    name: 'Red',
    amount: 0,
    mps: 1,
    totalMps: 0,
    multiplier: 1,
    cost: 1,
    moneyReq: 0,
    isUnlocked: false,
  },
  {
    id: 2,
    name: 'Orange',
    amount: 0,
    mps: 5,
    totalMps: 0,
    multiplier: 1,
    cost: 10,
    moneyReq: 5,
    isUnlocked: false,
  },
  {
    id: 3,
    name: 'Yellow',
    amount: 0,
    mps: 10,
    totalMps: 0,
    multiplier: 1,
    cost: 100,
    moneyReq: 50,
    isUnlocked: false,
  },
  {
    id: 4,
    name: 'LightGreen',
    amount: 0,
    mps: 10,
    totalMps: 0,
    multiplier: 1,
    cost: 100,
    moneyReq: 50,
    isUnlocked: false,
  },
  {
    id: 5,
    name: 'DarkGreen',
    amount: 0,
    mps: 10,
    totalMps: 0,
    multiplier: 1,
    cost: 100,
    moneyReq: 50,
    isUnlocked: false,
  },
  {
    id: 6,
    name: 'LightBlue',
    amount: 0,
    mps: 10,
    totalMps: 0,
    multiplier: 1,
    cost: 100,
    moneyReq: 50,
    isUnlocked: false,
  },
  {
    id: 7,
    name: 'DarkBlue',
    amount: 0,
    mps: 10,
    totalMps: 0,
    multiplier: 1,
    cost: 100,
    moneyReq: 50,
    isUnlocked: false,
  },
  {
    id: 8,
    name: 'Pink',
    amount: 0,
    mps: 10,
    totalMps: 0,
    multiplier: 1,
    cost: 100,
    moneyReq: 50,
    isUnlocked: false,
  },
  {
    id: 9,
    name: 'Purple',
    amount: 0,
    mps: 10,
    totalMps: 0,
    multiplier: 1,
    cost: 100,
    moneyReq: 50,
    isUnlocked: false,
  },
];
